classDiagram

    class Renter {
        +int RenterID
        +string Name
        +string Email
        +string PhoneNumber
        +string Address
        +int PayementMethodID
    }

    class Rack {
        +int Number
        +bool IsAvailable
        +DateTime StartDate
    }

    class PaymentMethod {
        +int PayementMethodID
        +string Name
    }

    Renter "1" -- "*" Rack : renter
    Renter "1" -- "1" PaymentMethod : paymentMethod
   